# Generated by Django 4.2 on 2023-04-25 19:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("year", models.CharField(max_length=10)),
                ("genre", models.CharField(max_length=255)),
                ("plot", models.CharField(max_length=2000)),
                ("lang", models.CharField(default="English", max_length=255)),
                (
                    "poster",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("trailor", embed_video.fields.EmbedVideoField(null=True)),
                ("runtime", models.CharField(max_length=100, null=True)),
                ("budget", models.CharField(max_length=100, null=True)),
                ("revenue", models.CharField(max_length=100, null=True)),
                ("director", models.CharField(max_length=100, null=True)),
                ("director_img", models.CharField(max_length=1000, null=True)),
                ("top_cast", models.CharField(max_length=100, null=True)),
                ("top_cast_img", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Viewer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("dob", models.DateField()),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="ViewerMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched", models.IntegerField(null=True)),
                ("favourite", models.IntegerField(null=True)),
                ("rating", models.IntegerField(null=True)),
                ("review", models.CharField(max_length=150, null=True)),
                ("rtime", models.DateTimeField(null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.movie"
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.viewer"
                    ),
                ),
            ],
        ),
    ]
