# Generated by Django 4.2 on 2023-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="revenue",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="top_cast",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
